echo !!Updating \"Twisted\"...
echo !!Running git pull...
git pull
echo !!Migrating...
uv run manage.py migrate
echo !!Building css...
uv run manage.py tailwind build
echo !!Deleting old static...
rm -r staticfiles/
echo !!Collecting static...
uv run manage.py collectstatic --noinput
echo !!Restarting services...
sudo systemctl restart autostart
echo !!Done! Now just wait ig.