# Generated by Django 6.0.2 on 2026-02-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_kvpairs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KVPairs',
            new_name='KVPair',
        ),
    ]
