# Generated by Django 6.0.2 on 2026-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_kvpairs_kvpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvpair',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
